[32m[I 2025-05-13 19:18:38,577][0m Trial 0 finished with value: 0.2268912126373608 and parameters: {'lr': 0.0003792028583399649, 'weight_decay': 0.00015678352296668067, 'batch_size': 32, 'n_layers': 4, 'hidden_dim': 1024}. Best is trial 0 with value: 0.2268912126373608.[0m
[Epoch 1/5] train_loss=0.2579 | val_loss=0.2187
[Epoch 2/5] train_loss=0.2314 | val_loss=0.2208
[Epoch 3/5] train_loss=0.1705 | val_loss=0.2401
[Epoch 4/5] train_loss=0.1012 | val_loss=0.2242
[Epoch 5/5] train_loss=0.0918 | val_loss=0.2269
/home/panda/Soccer/train.py:442: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  lr = trial.suggest_loguniform("lr", 1e-5, 1e-3)
/home/panda/Soccer/train.py:443: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-6, 1e-2)
Computing stats:  33%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž                                                                    | 1/3 [00:03<00:07,  3.88s/it]
[33m[W 2025-05-13 19:18:42,456][0m Trial 1 failed with parameters: {'lr': 0.000634425470345952, 'weight_decay': 1.895390871600482e-05, 'batch_size': 128, 'n_layers': 4, 'hidden_dim': 256} because of the following error: KeyboardInterrupt().[0m
Traceback (most recent call last):
  File "/home/panda/miniconda3/lib/python3.12/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/panda/Soccer/train.py", line 481, in <lambda>
    lambda t: _objective(t, train_paths, val_paths, epochs, target_type),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panda/Soccer/train.py", line 451, in _objective
    stats = compute_stats(train_paths)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panda/Soccer/train.py", line 220, in compute_stats
    shard = pickle.load(f)
            ^^^^^^^^^^^^^^
  File "/home/panda/miniconda3/lib/python3.12/site-packages/torch/storage.py", line 529, in _load_from_bytes
    def _load_from_bytes(b):

KeyboardInterrupt
[33m[W 2025-05-13 19:18:42,457][0m Trial 1 failed with value None.[0m
Traceback (most recent call last):
  File "/home/panda/Soccer/train.py", line 507, in <module>
    run_optuna(args.shards, args.trials, args.epochs, args.target)
  File "/home/panda/Soccer/train.py", line 480, in run_optuna
    study.optimize(
  File "/home/panda/miniconda3/lib/python3.12/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/panda/miniconda3/lib/python3.12/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/panda/miniconda3/lib/python3.12/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panda/miniconda3/lib/python3.12/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/panda/miniconda3/lib/python3.12/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/panda/Soccer/train.py", line 481, in <lambda>
    lambda t: _objective(t, train_paths, val_paths, epochs, target_type),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panda/Soccer/train.py", line 451, in _objective
    stats = compute_stats(train_paths)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panda/Soccer/train.py", line 220, in compute_stats
    shard = pickle.load(f)
            ^^^^^^^^^^^^^^
  File "/home/panda/miniconda3/lib/python3.12/site-packages/torch/storage.py", line 529, in _load_from_bytes
    def _load_from_bytes(b):

KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7a6740286b60>
Traceback (most recent call last):
  File "/home/panda/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/panda/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/panda/miniconda3/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/panda/miniconda3/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/home/panda/miniconda3/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
